//! Scenario: collateral_01_manual_update
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{app::LanaApp, primitives::*};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.collateral_01_manual_update_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn collateral_01_manual_update_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting collateral_01_manual_update scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;

    // Update collateral (standalone)
    // Note: This requires an existing pending facility
    // TODO: Track collateral_id properly
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Update collateral (standalone)
    // Note: This requires an existing pending facility
    // TODO: Track collateral_id properly
    // Advance time: 2 days
    for _ in 0..2 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Update collateral (standalone)
    // Note: This requires an existing pending facility
    // TODO: Track collateral_id properly

    event!(tracing::Level::INFO, "Completed collateral_01_manual_update scenario");
    Ok(())
}