//! Scenario: deposit_05_large_withdrawal
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{
    app::LanaApp, 
    primitives::*,
    terms::{DisbursalPolicy, FacilityDuration, InterestInterval, ObligationDuration, TermValues},
};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.deposit_05_large_withdrawal_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn deposit_05_large_withdrawal_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting deposit_05_large_withdrawal scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;

    // Make deposit for deposit_1
    let deposit_amount = UsdCents::try_from_usd(dec!(100000.0))?;
    helpers::make_deposit(&sub, app, &deposit_1_id, deposit_amount).await?;
    // Advance time: 2 days
    for _ in 0..2 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // TODO: WithdrawalEvent::ApprovalProcessConcluded

    event!(tracing::Level::INFO, "Completed deposit_05_large_withdrawal scenario");
    Ok(())
}