//! Scenario: edge_05_committee
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{app::LanaApp, primitives::*};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.edge_05_committee_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn edge_05_committee_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting edge_05_committee scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Create facility proposal
    let cf_terms = helpers::std_terms();  // TODO: customize terms from {'annual_rate': '0.09', 'duration': {'Months': 12}, 'interest_due_duration_from_accrual': {'Days': 30}, 'accrual_cycle_interval': 'EndOfMonth', 'accrual_interval': 'EndOfDay', 'one_time_fee_rate': '0.01', 'liquidation_cvl': {'Finite': '1.10'}, 'margin_call_cvl': {'Finite': '1.25'}, 'initial_cvl': {'Finite': '1.40'}, 'disbursal_policy': 'SingleDisbursal'}
    let cf_amount = UsdCents::try_from_usd(dec!(50000.0))?;
    let cf_proposal = app
        .create_facility_proposal(&sub, customer_1_id, cf_amount, cf_terms, None::<CustodianId>)
        .await?;
    let proposal_id = cf_proposal.id;
    let cf_id: CreditFacilityId = proposal_id.into();

    // Wait for approval process to conclude
    loop {
        tokio::select! {
            Some(msg) = stream.next() => {
                if let Some(LanaEvent::Credit(CoreCreditEvent::FacilityProposalConcluded {
                    entity,
                })) = &msg.payload
                    && entity.status == CreditFacilityProposalStatus::Approved
                    && entity.id == proposal_id
                {
                    msg.inject_trace_parent();
                    break;
                }
            }
            _ = tokio::time::sleep(EVENT_WAIT_TIMEOUT) => {
                clock_ctrl.advance(ONE_DAY).await;
            }
        }
    }

    event!(tracing::Level::INFO, "Completed edge_05_committee scenario");
    Ok(())
}