//! Scenario: edge_06_reports
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{
    app::LanaApp, 
    primitives::*,
    terms::{DisbursalPolicy, FacilityDuration, InterestInterval, ObligationDuration, TermValues},
};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.edge_06_reports_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn edge_06_reports_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting edge_06_reports scenario");

    let mut stream = app.outbox().listen_persisted(None);


    event!(tracing::Level::INFO, "Completed edge_06_reports scenario");
    Ok(())
}