//! Scenario: loan_10_customer_cancels
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{
    app::LanaApp, 
    primitives::*,
    terms::{DisbursalPolicy, FacilityDuration, InterestInterval, ObligationDuration, TermValues},
};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.loan_10_customer_cancels_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn loan_10_customer_cancels_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting loan_10_customer_cancels scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Create facility proposal
    let cf_terms = TermValues::builder()
        .annual_rate(dec!(10.00))
        .initial_cvl(dec!(140.00))
        .margin_call_cvl(dec!(125.00))
        .liquidation_cvl(dec!(110.00))
        .duration(FacilityDuration::Months(6))
        .interest_due_duration_from_accrual(ObligationDuration::Days(30))
        .obligation_overdue_duration_from_due(ObligationDuration::Days(50))
        .obligation_liquidation_duration_from_due(None)
        .accrual_interval(InterestInterval::EndOfDay)
        .accrual_cycle_interval(InterestInterval::EndOfMonth)
        .one_time_fee_rate(dec!(0.01))
        .disbursal_policy(DisbursalPolicy::SingleDisbursal)
        .build()
        .expect("terms builder should be valid");
    let cf_amount = UsdCents::try_from_usd(dec!(5000.0))?;
    let cf_proposal = app
        .create_facility_proposal(&sub, customer_1_id, cf_amount, cf_terms, None::<CustodianId>)
        .await?;
    let proposal_id = cf_proposal.id;
    let cf_id: CreditFacilityId = proposal_id.into();
    // Advance time: 2 days
    for _ in 0..2 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Customer approves proposal
    app.credit()
        .proposals()
        .conclude_customer_approval(&sub, proposal_id, true)
        .await?;

    event!(tracing::Level::INFO, "Completed loan_10_customer_cancels scenario");
    Ok(())
}