//! Scenario: loan_10_customer_cancels
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{app::LanaApp, primitives::*};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.loan_10_customer_cancels_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn loan_10_customer_cancels_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting loan_10_customer_cancels scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Create facility proposal
    let cf_terms = helpers::std_terms();  // TODO: customize terms from {'annual_rate': '0.10', 'duration': {'Months': 6}, 'interest_due_duration_from_accrual': {'Days': 30}, 'accrual_cycle_interval': 'EndOfMonth', 'accrual_interval': 'EndOfDay', 'one_time_fee_rate': '0.01', 'liquidation_cvl': {'Finite': '1.10'}, 'margin_call_cvl': {'Finite': '1.25'}, 'initial_cvl': {'Finite': '1.40'}, 'disbursal_policy': 'SingleDisbursal'}
    let cf_amount = UsdCents::try_from_usd(dec!(5000.0))?;
    let cf_proposal = app
        .create_facility_proposal(&sub, customer_1_id, cf_amount, cf_terms, None::<CustodianId>)
        .await?;
    let proposal_id = cf_proposal.id;
    let cf_id: CreditFacilityId = proposal_id.into();
    // Advance time: 2 days
    for _ in 0..2 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Customer approves proposal
    app.credit()
        .proposals()
        .conclude_customer_approval(&sub, proposal_id, true)
        .await?;

    event!(tracing::Level::INFO, "Completed loan_10_customer_cancels scenario");
    Ok(())
}