//! Scenario: loan_05_default
//! 
//! Generated by lana-sim-scenarios

use std::time::Duration;

use es_entity::clock::{ClockController, ClockHandle};
use futures::StreamExt;
use lana_app::{app::LanaApp, primitives::*};
use lana_events::{CoreCreditCollectionEvent, CoreCreditEvent, LanaEvent};
use rust_decimal_macros::dec;
use tracing::{event, instrument};

use crate::helpers;

const ONE_DAY: Duration = Duration::from_secs(86400);
const EVENT_WAIT_TIMEOUT: Duration = Duration::from_millis(100);

#[instrument(
    name = "sim_bootstrap.loan_05_default_scenario",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn loan_05_default_scenario(
    sub: Subject,
    app: &LanaApp,
    clock: &ClockHandle,
    clock_ctrl: &ClockController,
) -> anyhow::Result<()> {
    event!(tracing::Level::INFO, "Starting loan_05_default scenario");

    let mut stream = app.outbox().listen_persisted(None);


    // Create customer: customer_1
    let (customer_1_id, customer_1_deposit_id) = 
        helpers::create_customer(&sub, app, "1").await?;

    // Update collateral (standalone)
    // Note: This requires an existing pending facility
    // TODO: Track collateral_id properly
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Create facility proposal
    let cf_terms = helpers::std_terms();  // TODO: customize terms from {'annual_rate': '0.15', 'duration': {'Months': 6}, 'interest_due_duration_from_accrual': {'Days': 15}, 'obligation_overdue_duration_from_due': {'Days': 15}, 'obligation_liquidation_duration_from_due': {'Days': 30}, 'accrual_cycle_interval': 'EndOfMonth', 'accrual_interval': 'EndOfDay', 'one_time_fee_rate': '0.02', 'liquidation_cvl': {'Finite': '1.05'}, 'margin_call_cvl': {'Finite': '1.15'}, 'initial_cvl': {'Finite': '1.25'}, 'disbursal_policy': 'SingleDisbursal'}
    let cf_amount = UsdCents::try_from_usd(dec!(10000.0))?;
    let cf_proposal = app
        .create_facility_proposal(&sub, customer_1_id, cf_amount, cf_terms, None::<CustodianId>)
        .await?;
    let proposal_id = cf_proposal.id;
    let cf_id: CreditFacilityId = proposal_id.into();

    // Customer approves proposal
    app.credit()
        .proposals()
        .conclude_customer_approval(&sub, proposal_id, true)
        .await?;

    // Wait for approval process to conclude
    loop {
        tokio::select! {
            Some(msg) = stream.next() => {
                if let Some(LanaEvent::Credit(CoreCreditEvent::FacilityProposalConcluded {
                    entity,
                })) = &msg.payload
                    && entity.status == CreditFacilityProposalStatus::Approved
                    && entity.id == proposal_id
                {
                    msg.inject_trace_parent();
                    break;
                }
            }
            _ = tokio::time::sleep(EVENT_WAIT_TIMEOUT) => {
                clock_ctrl.advance(ONE_DAY).await;
            }
        }
    }

    // Update collateral to trigger facility activation
    let pending_facility = app
        .credit()
        .pending_credit_facilities()
        .find_by_id(&sub, proposal_id)
        .await?
        .expect("pending facility exists");

    app.credit()
        .collaterals()
        .update_collateral_by_id(
            &sub,
            pending_facility.collateral_id,
            Satoshis::from(30000000_u64),
            clock.today(),
        )
        .await?;

    // Wait for facility activation
    loop {
        tokio::select! {
            Some(msg) = stream.next() => {
                if let Some(LanaEvent::Credit(CoreCreditEvent::FacilityActivated { entity })) = &msg.payload
                    && entity.id == cf_id
                {
                    msg.inject_trace_parent();
                    break;
                }
            }
            _ = tokio::time::sleep(EVENT_WAIT_TIMEOUT) => {
                clock_ctrl.advance(ONE_DAY).await;
            }
        }
    }
    // Advance time: 1 days
    for _ in 0..1 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Wait for disbursal to settle
    loop {
        tokio::select! {
            Some(msg) = stream.next() => {
                if let Some(LanaEvent::Credit(CoreCreditEvent::DisbursalSettled { entity })) = &msg.payload
                    && entity.credit_facility_id == cf_id
                {
                    msg.inject_trace_parent();
                    break;
                }
            }
            _ = tokio::time::sleep(EVENT_WAIT_TIMEOUT) => {
                clock_ctrl.advance(ONE_DAY).await;
            }
        }
    }
    // Advance time: 5 days
    for _ in 0..5 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Time advancement (handled by wait_days above)
    // Advance time: 15 days
    for _ in 0..15 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Time advancement (handled by wait_days above)
    // Advance time: 15 days
    for _ in 0..15 {
        clock_ctrl.advance(ONE_DAY).await;
    }

    // Time advancement (handled by wait_days above)

    // TODO: CollateralEvent::LiquidationStarted

    // TODO: CollateralEvent::LiquidationCompleted

    event!(tracing::Level::INFO, "Completed loan_05_default scenario");
    Ok(())
}