//! Generated sim-bootstrap scenarios
//! Generated by lana-sim-scenarios

mod collateral_01_manual_update;
mod collateral_02_custodian_sync;
mod collateral_03_topup;
mod collateral_04_withdrawal;
mod collateral_05_price_drop;
mod collateral_06_price_recovery;
mod customer_01_simple;
mod customer_02_kyc_approved;
mod customer_03_kyc_rejected;
mod customer_04_prospect_conversion;
mod customer_05_business;
mod deposit_01_success;
mod deposit_02_reverted;
mod deposit_03_withdrawal_success;
mod deposit_04_withdrawal_denied;
mod deposit_05_large_withdrawal;
mod edge_01_multi_year;
mod edge_02_concurrent;
mod edge_03_zero_interest;
mod edge_04_max_ltv;
mod edge_05_committee;
mod edge_06_reports;
mod edge_07_price_events;
mod edge_08_bootstrap;
mod loan_01_happy_path;
mod loan_02_proposal_denied;
mod loan_03_disbursal_denied;
mod loan_04_late_payment;
mod loan_05_default;
mod loan_06_margin_call_recovery;
mod loan_07_partial_liquidation;
mod loan_08_early_repayment;
mod loan_09_multiple_disbursals;
mod loan_10_customer_cancels;
mod loan_11_full_liquidation;
mod loan_12_long_term;
mod payment_01_on_time;
mod payment_02_overdue;
mod payment_03_defaulted;
mod payment_04_partial;
mod payment_05_overpayment;
mod payment_06_multi_allocation;

use es_entity::clock::{ClockController, ClockHandle};
use tracing::instrument;

use lana_app::{app::LanaApp, primitives::*};

#[instrument(
    name = "sim_bootstrap.generated_scenarios.run",
    skip(app, clock, clock_ctrl),
    err
)]
pub async fn run(
    sub: &Subject,
    app: &LanaApp,
    clock: ClockHandle,
    clock_ctrl: ClockController,
) -> anyhow::Result<(), anyhow::Error> {
    collateral_01_manual_update::collateral_01_manual_update_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    collateral_02_custodian_sync::collateral_02_custodian_sync_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    collateral_03_topup::collateral_03_topup_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    collateral_04_withdrawal::collateral_04_withdrawal_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    collateral_05_price_drop::collateral_05_price_drop_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    collateral_06_price_recovery::collateral_06_price_recovery_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    customer_01_simple::customer_01_simple_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    customer_02_kyc_approved::customer_02_kyc_approved_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    customer_03_kyc_rejected::customer_03_kyc_rejected_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    customer_04_prospect_conversion::customer_04_prospect_conversion_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    customer_05_business::customer_05_business_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    deposit_01_success::deposit_01_success_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    deposit_02_reverted::deposit_02_reverted_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    deposit_03_withdrawal_success::deposit_03_withdrawal_success_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    deposit_04_withdrawal_denied::deposit_04_withdrawal_denied_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    deposit_05_large_withdrawal::deposit_05_large_withdrawal_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_01_multi_year::edge_01_multi_year_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_02_concurrent::edge_02_concurrent_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_03_zero_interest::edge_03_zero_interest_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_04_max_ltv::edge_04_max_ltv_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_05_committee::edge_05_committee_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_06_reports::edge_06_reports_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_07_price_events::edge_07_price_events_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    edge_08_bootstrap::edge_08_bootstrap_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_01_happy_path::loan_01_happy_path_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_02_proposal_denied::loan_02_proposal_denied_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_03_disbursal_denied::loan_03_disbursal_denied_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_04_late_payment::loan_04_late_payment_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_05_default::loan_05_default_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_06_margin_call_recovery::loan_06_margin_call_recovery_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_07_partial_liquidation::loan_07_partial_liquidation_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_08_early_repayment::loan_08_early_repayment_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_09_multiple_disbursals::loan_09_multiple_disbursals_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_10_customer_cancels::loan_10_customer_cancels_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_11_full_liquidation::loan_11_full_liquidation_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    loan_12_long_term::loan_12_long_term_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_01_on_time::payment_01_on_time_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_02_overdue::payment_02_overdue_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_03_defaulted::payment_03_defaulted_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_04_partial::payment_04_partial_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_05_overpayment::payment_05_overpayment_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;
    payment_06_multi_allocation::payment_06_multi_allocation_scenario(sub.clone(), app, &clock, &clock_ctrl).await?;

    Ok(())
}